### ISSUE TITLE
Delaunay Not working 

### ISSUE THREAD

**Issue by sheikmansoorg** [pinkwerks/Maya-Scripts#2]
Hi need help,
Tried to use your script, I created an instance of delaunay class and passed the points as argument. When I call triangulate method, it is displaying only number of points, nothing else is happening. No change, even my points selection is as it is. I'm expecting a triangulated polygon mesh out of the selected locators.

**Comment by pinkwerks** [comment]
A few things. Thanks for flagging a script I was not the original author of... I would remove it, however I've decided to see why it wasn't working for myself.

I pushed a new version that cleaned up some tabs->spaces and annoying print things. I was able to get results with this mayapy script. Of course - replace the path to the .py file with your local repo.

you can replace the call triangulate with `triangulate(outType='faces')`if you want to generate faces.

```
from pymel.core import *
execfile(r"C:\Users\pink\Documents\GitHub\maya\scripts\delaunay.py")
import random

locatorNames = []

for x in range(5):
    x = random.random();
    y = random.random();
    sl = spaceLocator(p=[x, y, 0])
    locatorNames.append(sl.name())
    
d = Delaunay(locatorNames);

d.triangulate()
```
